# Generated by Django 6.1 on 2026-09-02 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.CharField(blank=True, max_length=500, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='links.link')),
            ],
        ),
    ]
